org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.java.installations.paths=/opt/jdks/java-8,/opt/jdks/java-17,/usr/lib/jvm/java-21-openjdk-amd64,/opt/jdks/java-25
minecraft_version=26.1
loom_version=1.17.20
loader_version=0.19.5
fabric_api_version=0.145.1+26.1
mod_version=1.0.0-r110
maven_group=cn.blockforge.generated
archives_base_name=meteor-miku
